channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.2.4
- pip:
  - mlflow
  - argparse==1.4.0
  - cloudpickle==2.0.0
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - typing-extensions==4.1.1
name: mlflow-env
